version: '3.8'
services:
  api:
    build:
      dockerfile: ./docker/dockerfile.dev
      context: .
    command: yarn start:dev
    ports:
      - "80:3000"
#    volumes:
#      - ./:/app/

  marketing-scylla-node:
    image: scylladb/scylla
    hostname: scylladb/scylla
    ports:
      - "9160:9160"
      - "9042:9042"