version: '3.8'
services:
  api:
    build:
      dockerfile: ./docker/dockerfile.live
      context: .
    command: yarn start:prod
    ports:
      - "80:3000"

#  marketing-scylla-node:
#    image: scylladb/scylla
#    hostname: scylladb/scylla
#    ports:
#      - "9160:9160"
#      - "9042:9042"