FROM node:18.12.1-alpine
WORKDIR /app
COPY package.json ./
ENV TZ=Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN yarn install
COPY . .
RUN yarn run build
CMD ["yarn", "start:local"]